-- MySQL Script generated by MySQL Workbench
-- seg 13 mar 2023 22:57:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `tipoUsuario` INT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `usuario_idUsuario` INT NOT NULL,
  `especie` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `dataAdocao` DATE NULL,
  `dataFalecimento` DATE NULL,
  `peso` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `sexo` VARCHAR(15) NULL,
  `notas` TEXT NULL,
  `imagem` VARCHAR(255) NULL,
  `raca` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnimal`),
  INDEX `fk_animal_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_animal_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `tcc`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`raca` (
  `idRaca` INT NOT NULL AUTO_INCREMENT,
  `raca` VARCHAR(45) NULL,
  `especie_idEspecie` INT NOT NULL,
  PRIMARY KEY (`idRaca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`agenda` (
  `idAgenda` INT NOT NULL AUTO_INCREMENT,
  `servico` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `observacao` VARCHAR(255) NULL,
  `dataAgenda` DATE NULL,
  `horario` VARCHAR(45) NULL,
  `animal_idAnimal` INT NOT NULL,
  PRIMARY KEY (`idAgenda`),
  INDEX `fk_agenda_animal1_idx` (`animal_idAnimal` ASC) ,
  CONSTRAINT `fk_agenda_animal1`
    FOREIGN KEY (`animal_idAnimal`)
    REFERENCES `tcc`.`animal` (`idAnimal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
